security:
    encoders:
        App\Entity\User: bcrypt
        App\Entity\Admin: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [user_db, admin_db]

        user_db:
            entity: { class: App\Entity\User, property: username }

        admin_db:
            entity: { class: App\Entity\Admin, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: index
            logout:
                path: /logout
                target: /login
            provider: chain_provider

    access_control:
        - { path: ^/post/create, roles: ROLE_ADMIN }
        - { path: ^/post/show/*, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/post/delete/*, roles: ROLE_ADMIN }
        - { path: ^/dashboard/posts, roles: ROLE_ADMIN }
        - { path: ^/dashboard/comments, roles: ROLE_ADMIN }


