security:
    encoders:
        App\Entity\User: bcrypt
        App\Entity\Admin: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [user_db, admin_db]

        user_db:
            entity: { class: App\Entity\User, property: username }

        admin_db:
            entity: { class: App\Entity\Admin, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login
            provider: chain_provider

    access_control:
        - { path: ^/post/*, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
