#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\PostsController::list

about:
    path: /about
    controller: App\Controller\HomeController::about

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

services:
    path: /services
    controller: App\Controller\HomeController::services

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

register:
    path: /register
    controller: App\Controller\RegistrationController::register

post_create:
    path: /post/create
    controller: App\Controller\PostsController::create

post_show:
    path: /post/show/{id}
    controller: App\Controller\PostsController::show

post_edit:
    path: /post/edit/{id}
    controller: App\Controller\PostsController::edit

post_delete:
    path: /post/delete/{id}
    controller: App\Controller\PostsController::delete

post_category_list:
    path: /post/category/{id}
    controller: App\Controller\PostsController::listCategory

comment_edit:
    path: /comment/edit/{id}
    controller: App\Controller\CommentsController::edit

comment_delete:
    path: /comment/delete/{id}
    controller: App\Controller\CommentsController::delete

dashboard_posts:
    path: /dashboard/posts
    controller: App\Controller\DashboardController::posts

dashboard_comments:
    path: /dashboard/comments
    controller: App\Controller\DashboardController::comments