#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\HomeController::about

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

services:
    path: /services
    controller: App\Controller\HomeController::services

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

register:
    path: /register
    controller: App\Controller\RegistrationController::register

post_create:
    path: /post/create
    controller: App\Controller\PostsController::create

post_show:
    path: /post/show/{id}
    controller: App\Controller\PostsController::show

